php:
  preset: laravel
js:
  finder:
    exclude:
      - bin
      - modules
      - node_modules
      - storage
      - vendor
    name:
      - "*.js"
      - "*.jsx"
    not-name:
      - "*.min.js"
css: true
